//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.NG.Routing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about
    {
        public string mission { get; set; }
        public string address { get; set; }
        public string exec_board { get; set; }
        public string practices { get; set; }
        public int id { get; set; }
    }
}
