//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.NG.Routing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_list
    {
        public int event_id { get; set; }
        public int ticket_id { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public System.DateTime start_date { get; set; }
        public decimal fee { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int id { get; set; }
    }
}
