//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.NG.Routing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallery
    {
        public int photo_id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
    }
}
