//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.NG.Routing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public string uta_id { get; set; }
        public int event_id { get; set; }
        public int ticket_id { get; set; }
    }
}
