//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.NG.Routing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string uta_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string role { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_activity { get; set; }
    }
}
