//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.NG.Routing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class utawaterpoloEntities : DbContext
    {
        public utawaterpoloEntities()
            : base("name=utawaterpoloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> abouts { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<event_list> event_list { get; set; }
        public virtual DbSet<gallery> galleries { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int getEventList(string uta_id)
        {
            var uta_idParameter = uta_id != null ?
                new ObjectParameter("uta_id", uta_id) :
                new ObjectParameter("uta_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getEventList", uta_idParameter);
        }
    }
}
